### ISSUE TITLE
No matching distribution found for pydub.silence and the rest

### ISSUE THREAD

**Issue by MrCarJrProductions** [atharvjairath/Tacotron-2-Dataset-Creator#1]
ERROR: Could not find a version that satisfies the requirement pydub.silence (from versions: none)
ERROR: No matching distribution found for pydub.silence
how do i fix this?
also update the readme.md

**Comment by atharvjairath** [comment]
Hey, I have added the requirement file for the required installation of libraries. You can pull the new commit. That should fix it. Also added readme (incomplete) but should get the work done

**Comment by MrCarJrProductions** [comment]
I got this
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by MrCarJrProductions** [comment]
What's worse is that the file already exists. I mean LOOK AT THIS
![BRO IT'S LITERALLY RIGHT THERE](https://user-images.githubusercontent.com/111096511/185813435-a38c68eb-4df6-4868-a0c9-9b925c85df08.PNG)
.

**Comment by MrCarJrProductions** [comment]
I drew the circles and arrows with my mouse

**Comment by MrCarJrProductions** [comment]
In fact, 'requirements.txt' is spelled correctly in BOTH circles.

**Comment by MrCarJrProductions** [comment]
Can't believe that this still hasn't been solved

**Comment by MrCarJrProductions** [comment]
YKW? forget it.

**Comment by atharvjairath** [comment]
@MrCarJrProductions ,
Hi, First of all, I am a student, who just uploaded the code so others can use it. There is no need to be rude about it If I by-mistake miss the issue. I am not maintaining it, I do not have the time for it
second, you need to do: `%cd Tacotron-2-Dataset-Creator` after cloning the repo.
